/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as PlansPlanSlugRouteImport } from './routes/plans/$planSlug'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansPlanSlugRoute = PlansPlanSlugRouteImport.update({
  id: '/plans/$planSlug',
  path: '/plans/$planSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans/$planSlug': typeof PlansPlanSlugRoute
  '/account/': typeof AccountIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans/$planSlug': typeof PlansPlanSlugRoute
  '/account': typeof AccountIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/recipes': typeof RecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans/$planSlug': typeof PlansPlanSlugRoute
  '/account/': typeof AccountIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/recipes/': typeof RecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plans/$planSlug' | '/account/' | '/privacy/' | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plans/$planSlug' | '/account' | '/privacy' | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/plans/$planSlug'
    | '/account/'
    | '/privacy/'
    | '/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansPlanSlugRoute: typeof PlansPlanSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans/$planSlug': {
      id: '/plans/$planSlug'
      path: '/plans/$planSlug'
      fullPath: '/plans/$planSlug'
      preLoaderRoute: typeof PlansPlanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansPlanSlugRoute: PlansPlanSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
